#!/usr/bin/env python3
"""Analyze Auctioneer SQLite database contents and print summary metrics.

This script is designed for databases generated by auctioneer_rope_to_sqlite.py,
but it will inspect any SQLite file and report table counts, distinct values,
duplicate rows, text lengths, and SQLite encoding/page metrics.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


@dataclass
class ColumnInfo:
    cid: int
    name: str
    type: str
    notnull: int
    dflt_value: Optional[str]
    pk: int


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def format_bytes(value: int) -> str:
    if value < 1024:
        return f"{value} B"
    for unit in ["KB", "MB", "GB", "TB"]:
        value /= 1024.0
        if value < 1024.0:
            return f"{value:.2f} {unit}"
    return f"{value:.2f} PB"


def safe_fetchone(
    cursor: sqlite3.Cursor, query: str, params: Tuple[Any, ...] = ()
) -> Optional[Tuple[Any, ...]]:
    try:
        return cursor.execute(query, params).fetchone()
    except sqlite3.DatabaseError as error:
        print(f"WARNING: query failed: {query}\n  {error}", file=sys.stderr)
        return None


def get_tables(conn: sqlite3.Connection) -> List[str]:
    cursor = conn.cursor()
    rows = cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [row[0] for row in rows]


def get_table_columns(conn: sqlite3.Connection, table: str) -> List[ColumnInfo]:
    cursor = conn.cursor()
    rows = cursor.execute(f"PRAGMA table_info({quote_ident(table)})").fetchall()
    return [ColumnInfo(*row) for row in rows]


def count_rows(conn: sqlite3.Connection, table: str) -> int:
    cursor = conn.cursor()
    row = safe_fetchone(cursor, f"SELECT COUNT(*) FROM {quote_ident(table)}")
    return int(row[0]) if row is not None else 0


def count_distinct(conn: sqlite3.Connection, table: str, column: str) -> Optional[int]:
    cursor = conn.cursor()
    row = safe_fetchone(
        cursor,
        f"SELECT COUNT(DISTINCT {quote_ident(column)}) FROM {quote_ident(table)}",
    )
    return int(row[0]) if row is not None else None


def count_nulls(conn: sqlite3.Connection, table: str, column: str) -> Optional[int]:
    cursor = conn.cursor()
    row = safe_fetchone(
        cursor,
        f"SELECT SUM({quote_ident(column)} IS NULL) FROM {quote_ident(table)}",
    )
    return int(row[0]) if row is not None and row[0] is not None else 0


def min_avg_max_length(
    conn: sqlite3.Connection, table: str, column: str
) -> Tuple[Optional[int], Optional[float], Optional[int]]:
    cursor = conn.cursor()
    row = safe_fetchone(
        cursor,
        f"SELECT MIN(LENGTH({quote_ident(column)})), AVG(LENGTH({quote_ident(column)})), MAX(LENGTH({quote_ident(column)})) FROM {quote_ident(table)}",
    )
    if row is None:
        return None, None, None
    return (
        int(row[0]) if row[0] is not None else None,
        float(row[1]) if row[1] is not None else None,
        int(row[2]) if row[2] is not None else None,
    )


def top_values(
    conn: sqlite3.Connection, table: str, column: str, limit: int = 10
) -> List[Tuple[Any, int]]:
    cursor = conn.cursor()
    query = (
        f"SELECT {quote_ident(column)}, COUNT(*) AS cnt FROM {quote_ident(table)} "
        f"WHERE {quote_ident(column)} IS NOT NULL GROUP BY {quote_ident(column)} "
        f"ORDER BY cnt DESC LIMIT {limit}"
    )
    try:
        return [(row[0], int(row[1])) for row in cursor.execute(query).fetchall()]
    except sqlite3.DatabaseError:
        return []


def count_exact_duplicate_rows(
    conn: sqlite3.Connection, table: str, columns: Sequence[str]
) -> Optional[int]:
    if not columns:
        return None
    cursor = conn.cursor()
    column_list = ", ".join(quote_ident(col) for col in columns)
    query = (
        f"SELECT SUM(cnt - 1) FROM ("
        f"SELECT COUNT(*) AS cnt FROM {quote_ident(table)} "
        f"GROUP BY {column_list} HAVING cnt > 1)"
    )
    row = safe_fetchone(cursor, query)
    return int(row[0]) if row is not None and row[0] is not None else 0


def analyze_rope_json(conn: sqlite3.Connection, table: str) -> Dict[str, Any]:
    cursor = conn.cursor()
    stats = {
        "decoded_rows": 0,
        "json_parse_errors": 0,
        "rope_length_min": None,
        "rope_length_max": None,
        "rope_length_avg": None,
        "byte_length_min": None,
        "byte_length_max": None,
        "byte_length_avg": None,
    }

    lengths: List[int] = []
    byte_lengths: List[int] = []
    total = 0

    for row in cursor.execute(
        f"SELECT decoded_json FROM {quote_ident(table)} WHERE decoded_json IS NOT NULL"
    ):
        total += 1
        text = row[0]
        if text is None:
            continue
        try:
            decoded = json.loads(text)
        except Exception:
            stats["json_parse_errors"] += 1
            continue

        if isinstance(decoded, dict):
            if "rope_length" in decoded and isinstance(decoded["rope_length"], int):
                lengths.append(decoded["rope_length"])
            if "byte_length" in decoded and isinstance(decoded["byte_length"], int):
                byte_lengths.append(decoded["byte_length"])
            stats["decoded_rows"] += 1

    if lengths:
        stats["rope_length_min"] = min(lengths)
        stats["rope_length_max"] = max(lengths)
        stats["rope_length_avg"] = sum(lengths) / len(lengths)
    if byte_lengths:
        stats["byte_length_min"] = min(byte_lengths)
        stats["byte_length_max"] = max(byte_lengths)
        stats["byte_length_avg"] = sum(byte_lengths) / len(byte_lengths)
    return stats


def analyze_parsed_json(conn: sqlite3.Connection, table: str) -> Dict[str, Any]:
    cursor = conn.cursor()
    stats = {
        "parsed_rows": 0,
        "json_parse_errors": 0,
        "item_id_null": 0,
        "item_name_null": 0,
    }
    for row in cursor.execute(f"SELECT parsed_json, item_id, item_name FROM {quote_ident(table)}"):
        text, item_id, item_name = row
        if text is not None:
            try:
                _ = json.loads(text)
            except Exception:
                stats["json_parse_errors"] += 1
            else:
                stats["parsed_rows"] += 1
        if item_id is None:
            stats["item_id_null"] += 1
        if item_name is None:
            stats["item_name_null"] += 1
    return stats


def fetch_rows_with_rowid(
    conn: sqlite3.Connection, table: str, columns: Sequence[str]
) -> List[Tuple[Any, ...]]:
    cursor = conn.cursor()
    select_columns = ", ".join(quote_ident(col) for col in columns)
    query = f"SELECT rowid, {select_columns} FROM {quote_ident(table)} ORDER BY rowid"
    try:
        return cursor.execute(query).fetchall()
    except sqlite3.DatabaseError:
        return []


def analyze_auctioneer_compile_metadata(conn: sqlite3.Connection, table: str) -> None:
    row_count = count_rows(conn, table)
    print(f"  compile metadata rows: {row_count}")
    if row_count == 0:
        return
    cursor = conn.cursor()
    ordered = [
        "entry_id",
        "input_path",
        "input_size",
        "input_mtime",
        "parsed_type",
        "string_rows",
        "scan_servers",
        "scan_factions",
        "scan_data_tables",
        "image_rows",
        "rope_strings",
        "rope_rows",
        "top_level_listing_dicts",
        "top_level_listing_list_rows",
        "compiled_at",
        "generator_script",
        "python_version",
    ]
    query = f"SELECT {', '.join(quote_ident(c) for c in ordered)} FROM {quote_ident(table)} ORDER BY entry_id"
    rows = cursor.execute(query).fetchall()
    if not rows:
        return
    if row_count == 1:
        values = dict(zip(ordered, rows[0]))
        for key, value in values.items():
            print(f"    - {key}: {value}")
        return
    print("    - sample entries:")
    for sample_name, row in [("first", rows[0]), ("last", rows[-1])]:
        values = dict(zip(ordered, row))
        print(f"      {sample_name}:")
        for key in [
            "input_path",
            "parsed_type",
            "string_rows",
            "scan_servers",
            "scan_factions",
            "scan_data_tables",
            "image_rows",
            "rope_strings",
            "rope_rows",
            "top_level_listing_dicts",
            "top_level_listing_list_rows",
            "compiled_at",
        ]:
            print(f"        {key}: {values.get(key)}")


def analyze_auction_listings_id_pattern(conn: sqlite3.Connection, table: str) -> None:
    columns = [col.name for col in get_table_columns(conn, table)]
    row_count = count_rows(conn, table)

    if "id" not in columns:
        print("  auctionListings id check: no id column present")
        return

    nulls = count_nulls(conn, table, "id")
    distinct = count_distinct(conn, table, "id")
    print(f"  auctionListings id column: null={nulls}, distinct={distinct}")
    if nulls == row_count:
        print("    - id is entirely NULL in this dataset")
    elif distinct is not None:
        dup_count = safe_fetchone(
            conn,
            f"SELECT COUNT(*) - COUNT(DISTINCT {quote_ident('id')}) FROM {quote_ident(table)} WHERE {quote_ident('id')} IS NOT NULL",
        )
        if dup_count is not None:
            dup_count = int(dup_count[0])
            print(f"    - duplicate non-null ids: {dup_count}")
        if distinct == row_count and nulls == 0:
            print("    - id values are unique for every row")
        else:
            print("    - id values are not a guaranteed unique primary identifier")

    if row_count < 2:
        return

    rows = fetch_rows_with_rowid(conn, table, columns)
    if not rows:
        return
    compare_cols = tuple(range(1, len(rows[0])))

    def row_values(row):
        return tuple(row[i] for i in compare_cols)

    pair_matches = 0
    pair_total = row_count // 2
    for i in range(0, pair_total * 2, 2):
        if row_values(rows[i]) == row_values(rows[i + 1]):
            pair_matches += 1
    if pair_total:
        ratio = pair_matches / pair_total
        print(
            f"  auctionListings adjacent-pair duplicate ratio: {pair_matches}/{pair_total} ({ratio:.2%})"
        )
        if ratio >= 0.95:
            print("    - pattern detected: every 2 rows are identical or nearly identical")

    if row_count % 2 == 0:
        half = row_count // 2
        half_matches = 0
        for i in range(half):
            if row_values(rows[i]) == row_values(rows[i + half]):
                half_matches += 1
        ratio = half_matches / half
        print(f"  auctionListings half-repeat duplicate ratio: {half_matches}/{half} ({ratio:.2%})")
        if ratio >= 0.95:
            print("    - pattern detected: second half of rows repeats the first half")

    if row_count >= 4:
        second_half_pair_matches = 0
        second_half_total = (
            (row_count - half) // 2 if row_count % 2 == 0 else (row_count - half - 1) // 2
        )
        if second_half_total > 0:
            base_index = half
            for i in range(base_index, base_index + second_half_total * 2, 2):
                if row_values(rows[i]) == row_values(rows[i + 1]):
                    second_half_pair_matches += 1
            ratio = second_half_pair_matches / second_half_total
            print(
                f"  auctionListings second-half adjacent-pair duplicate ratio: {second_half_pair_matches}/{second_half_total} ({ratio:.2%})"
            )
            if ratio >= 0.95:
                print("    - pattern detected: second-half rows are duplicated in adjacent pairs")


def print_table_summary(conn: sqlite3.Connection, table: str) -> None:
    print(f"\nTable: {table}")
    columns = get_table_columns(conn, table)
    if not columns:
        print("  (no columns found)")
        return

    row_count = count_rows(conn, table)
    print(f"  rows: {row_count}")
    print("  columns:")
    for column in columns:
        print(f"    - {column.name} ({column.type or 'UNKNOWN'})")

    if row_count == 0:
        return

    print("  distinct / null counts:")
    for column in columns:
        distinct = count_distinct(conn, table, column.name)
        nulls = count_nulls(conn, table, column.name)
        if distinct is None:
            print(f"    - {column.name}: cannot compute distinct")
        else:
            print(f"    - {column.name}: distinct={distinct}, null={nulls}")

    text_columns = [
        col.name for col in columns if col.type and col.type.upper() in {"TEXT", "CHAR", "CLOB"}
    ]
    if text_columns:
        print("  text length stats:")
        for column_name in text_columns:
            min_len, avg_len, max_len = min_avg_max_length(conn, table, column_name)
            if min_len is None:
                continue
            print(f"    - {column_name}: min={min_len}, avg={avg_len:.1f}, max={max_len}")

    if row_count <= 200_000:
        all_columns = [col.name for col in columns]
        exact_dupes = count_exact_duplicate_rows(conn, table, all_columns)
        if exact_dupes is not None:
            print(f"  exact duplicate rows: {exact_dupes}")

    if table == "auctioneer_rope":
        stats = analyze_rope_json(conn, table)
        if stats["decoded_rows"] or stats["json_parse_errors"]:
            print("  auctioneer_rope decoded_json stats:")
            print(f"    - decoded_json rows with valid JSON: {stats['decoded_rows']}")
            print(f"    - decoded_json parse errors: {stats['json_parse_errors']}")
            if stats["rope_length_min"] is not None:
                print(
                    f"    - rope_length: min={stats['rope_length_min']}, avg={stats['rope_length_avg']:.1f}, max={stats['rope_length_max']}"
                )
            if stats["byte_length_min"] is not None:
                print(
                    f"    - byte_length: min={stats['byte_length_min']}, avg={stats['byte_length_avg']:.1f}, max={stats['byte_length_max']}"
                )
        raw_count = count_distinct(conn, table, "raw_rope")
        if raw_count is not None:
            print(f"  distinct raw_rope values: {raw_count}")

    if table == "auctioneer_item":
        stats = analyze_parsed_json(conn, table)
        print("  auctioneer_item parsed_json stats:")
        print(f"    - parsed_json rows with valid JSON: {stats['parsed_rows']}")
        print(f"    - parsed_json parse errors: {stats['json_parse_errors']}")
        print(f"    - item_id NULL count: {stats['item_id_null']}")
        print(f"    - item_name NULL count: {stats['item_name_null']}")
        if any(col.name == "raw_value" for col in columns):
            dup_raw = count_distinct(conn, table, "raw_value")
            if dup_raw is not None:
                print(f"    - distinct raw_value values: {dup_raw}")

    if table == "auctioneer_compile_metadata":
        analyze_auctioneer_compile_metadata(conn, table)

    if table == "auctioneer_rope":
        stats = analyze_rope_json(conn, table)
        if stats["decoded_rows"] or stats["json_parse_errors"]:
            print("  auctioneer_rope decoded_json stats:")
            print(f"    - decoded_json rows with valid JSON: {stats['decoded_rows']}")
            print(f"    - decoded_json parse errors: {stats['json_parse_errors']}")
            if stats["rope_length_min"] is not None:
                print(
                    f"    - rope_length: min={stats['rope_length_min']}, avg={stats['rope_length_avg']:.1f}, max={stats['rope_length_max']}"
                )
            if stats["byte_length_min"] is not None:
                print(
                    f"    - byte_length: min={stats['byte_length_min']}, avg={stats['byte_length_avg']:.1f}, max={stats['byte_length_max']}"
                )
        raw_count = count_distinct(conn, table, "raw_rope")
        if raw_count is not None:
            print(f"  distinct raw_rope values: {raw_count}")

    if table == "auctioneer_item":
        stats = analyze_parsed_json(conn, table)
        print("  auctioneer_item parsed_json stats:")
        print(f"    - parsed_json rows with valid JSON: {stats['parsed_rows']}")
        print(f"    - parsed_json parse errors: {stats['json_parse_errors']}")
        print(f"    - item_id NULL count: {stats['item_id_null']}")
        print(f"    - item_name NULL count: {stats['item_name_null']}")
        if any(col.name == "raw_value" for col in columns):
            dup_raw = count_distinct(conn, table, "raw_value")
            if dup_raw is not None:
                print(f"    - distinct raw_value values: {dup_raw}")

    if table == "auctionListings":
        print("  auctionListings highlights:")
        interesting = ["sellerName", "itemId", "itemName", "link", "buyoutPrice"]
        for column_name in interesting:
            if any(col.name == column_name for col in columns):
                distinct = count_distinct(conn, table, column_name)
                print(f"    - distinct {column_name}: {distinct}")
        seller_top = top_values(conn, table, "sellerName", limit=10)
        if seller_top:
            print("    - top sellers:")
            for value, count in seller_top:
                print(f"      {value!r}: {count}")
        item_top = top_values(conn, table, "itemName", limit=10)
        if item_top:
            print("    - top itemName values:")
            for value, count in item_top:
                print(f"      {value!r}: {count}")
        if all(
            any(col.name == c for col in columns)
            for c in [
                "sellerName",
                "itemId",
                "stackSize",
                "price",
                "buyoutPrice",
                "timeLeft",
                "seenTime",
                "link",
            ]
        ):
            dup_key_cols = [
                "sellerName",
                "itemId",
                "stackSize",
                "price",
                "buyoutPrice",
                "timeLeft",
                "seenTime",
                "link",
            ]
            duplicate_groups = count_exact_duplicate_rows(conn, table, dup_key_cols)
            print(
                f"    - duplicate listing groups by seller/item/stack/price/buyout/timeLeft/seenTime/link: {duplicate_groups}"
            )
        analyze_auction_listings_id_pattern(conn, table)


def analyze_db(path: Path) -> None:
    print(f"\n=== {path} ===")
    if not path.exists():
        print(f"ERROR: file not found: {path}")
        return
    print(f"file size: {path.stat().st_size} bytes ({format_bytes(path.stat().st_size)})")

    conn = sqlite3.connect(str(path))
    try:
        cursor = conn.cursor()
        pragmas = {
            "encoding": safe_fetchone(cursor, "PRAGMA encoding"),
            "page_size": safe_fetchone(cursor, "PRAGMA page_size"),
            "page_count": safe_fetchone(cursor, "PRAGMA page_count"),
            "freelist_count": safe_fetchone(cursor, "PRAGMA freelist_count"),
            "auto_vacuum": safe_fetchone(cursor, "PRAGMA auto_vacuum"),
            "journal_mode": safe_fetchone(cursor, "PRAGMA journal_mode"),
        }
        print("SQLite pragmas:")
        for name, value in pragmas.items():
            if value is None:
                continue
            print(f"  - {name}: {value[0]}")
        if pragmas["page_size"] and pragmas["page_count"]:
            page_size = int(pragmas["page_size"][0])
            page_count = int(pragmas["page_count"][0])
            print(
                f"  - total page bytes: {page_size * page_count} ({format_bytes(page_size * page_count)})"
            )

        tables = get_tables(conn)
        if not tables:
            print("No tables found in database.")
            return
        print(f"tables: {', '.join(tables)}")
        for table in tables:
            print_table_summary(conn, table)
    finally:
        conn.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze Auctioneer SQLite database contents")
    parser.add_argument(
        "paths",
        nargs="+",
        help="SQLite database files to analyze",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    for path_str in args.paths:
        analyze_db(Path(path_str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
