#!/usr/bin/env python3
"""Trace a single item across Auctioneer scan DBs and sales.db.

This script is designed to inspect SQLite databases generated by
`auctioneer_rope_to_sqlite.py` and the sales DB produced by
`AuctionScanDiff.py`.

Example:
  python trace_item_sales.py --item-name "Northern Spices" --scan-dir ./ --sales-db sales.db
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

log_data: Dict[str, Any] = {
    "item_name": "",
    "item_ids": [],
    "scan_dbs": [],
    "sales_db": {},
}


def append_scan_db(scan_entry: Dict[str, Any]) -> None:
    log_data["scan_dbs"].append(scan_entry)


def set_sales_db(sales_entry: Dict[str, Any]) -> None:
    log_data["sales_db"] = sales_entry


def write_json_output(path: Path) -> None:
    path.write_text(json.dumps(log_data, indent=2, sort_keys=True), encoding="utf-8")


def load_item_ids(item_names_path: Path, item_name: str) -> List[int]:
    text = item_names_path.read_text(encoding="utf-8")
    data = json.loads(text)
    matches = [int(key) for key, value in data.items() if isinstance(value, str) and value.lower() == item_name.lower()]
    if matches:
        return matches
    if item_name.isdigit():
        return [int(item_name)]
    raise ValueError(f"Unable to resolve item name to ID: {item_name}")


def format_timestamp(value: Optional[int]) -> str:
    if value is None:
        return "<none>"
    try:
        return datetime.fromtimestamp(int(value)).isoformat(sep=" ")
    except Exception:
        return str(value)


def quote_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def get_tables(conn: sqlite3.Connection) -> List[str]:
    cursor = conn.cursor()
    rows = cursor.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").fetchall()
    return [row[0] for row in rows]


def scan_db_rows(db_path: Path, item_ids: Sequence[int], item_name: str) -> None:
    if not db_path.exists():
        append_scan_db({
            "timestamp": None,
            "has_auctionListings": False,
            "compile_metadata": [],
            "matched_count": 0,
            "matches": [],
        })
        return

    with sqlite3.connect(db_path) as conn:
        tables = get_tables(conn)
        if "auctionListings" not in tables:
            append_scan_db({
                "timestamp": format_timestamp(int(db_path.stat().st_mtime)),
                "has_auctionListings": False,
                "compile_metadata": [],
                "matched_count": 0,
                "matches": [],
            })
            return

        metadata_rows = []
        if "auctioneer_compile_metadata" in tables:
            cursor = conn.cursor()
            metadata_rows = cursor.execute(
                "SELECT input_path, input_size, input_mtime, parsed_type, compiled_at FROM auctioneer_compile_metadata ORDER BY entry_id"
            ).fetchall()

        scan_entry: Dict[str, Any] = {
            "timestamp": format_timestamp(int(db_path.stat().st_mtime)),
            "has_auctionListings": True,
            "compiled_at": metadata_rows[0][4] if metadata_rows else None,
            "compile_metadata": [
                {
                    "input_size": input_size,
                    "input_mtime": format_timestamp(input_mtime),
                    "parsed_type": parsed_type,
                    "compiled_at": compiled_at,
                }
                for _, input_size, input_mtime, parsed_type, compiled_at in metadata_rows
            ],
            "matched_count": 0,
            "matches": [],
        }

        query = (
            "SELECT rowid, server, faction, ropeId, id, link, useLevel, itemLevel, itemType, subType, equipPos, price, timeLeft, seenTime, itemName, texture, stackSize, quality, canUse, minBid, curBid, increment, sellerName, buyoutPrice, amBidder, dataFlag, itemId, itemSuffix, itemFactor, itemEnchant, itemSeed "
            "FROM auctionListings "
            "WHERE itemId IN ({ids}) "
            "ORDER BY seenTime, rowid"
        ).format(ids=",".join("?" for _ in item_ids))

        cursor = conn.cursor()
        rows = cursor.execute(query, tuple(item_ids)).fetchall()
        if not rows:
            scan_entry["matches"] = []
            append_scan_db(scan_entry)
            return

        scan_entry["matched_count"] = len(rows)
        for row in rows:
            (
                rowid,
                server,
                faction,
                ropeId,
                lid,
                link,
                useLevel,
                itemLevel,
                itemType,
                subType,
                equipPos,
                price,
                timeLeft,
                seenTime,
                itemName,
                texture,
                stackSize,
                quality,
                canUse,
                minBid,
                curBid,
                increment,
                sellerName,
                buyoutPrice,
                amBidder,
                dataFlag,
                itemId,
                itemSuffix,
                itemFactor,
                itemEnchant,
                itemSeed,
            ) = row
            scan_entry["matches"].append(
                {
                    "rowid": rowid,
                    "seenTime": format_timestamp(seenTime),
                    "server": server,
                    "faction": faction,
                    "itemName": itemName,
                    "itemId": itemId,
                    "stackSize": stackSize,
                    "price": price,
                    "buyoutPrice": buyoutPrice,
                    "curBid": curBid,
                    "minBid": minBid,
                    "sellerName": sellerName,
                }
            )
        append_scan_db(scan_entry)


def sales_db_rows(sales_db_path: Path, item_ids: Sequence[int], item_name: str) -> None:
    if not sales_db_path.exists():
        set_sales_db({
            "timestamp": None,
            "has_sales_table": False,
            "matched_count": 0,
            "matches": [],
        })
        return

    with sqlite3.connect(sales_db_path) as conn:
        tables = get_tables(conn)
        sales_entry: Dict[str, Any] = {
            "timestamp": format_timestamp(int(sales_db_path.stat().st_mtime)),
            "has_sales_table": "sales" in tables,
            "matched_count": 0,
            "matches": [],
        }
        if "sales" not in tables:
            set_sales_db(sales_entry)
            return

        cursor = conn.cursor()
        rows = cursor.execute(
            "SELECT id, status, sold_likelihood, sold_likelihood_percent, elapsed_hours, peer_count, cheaper_peer_count, repost_average_unit_price, reason, listing_json FROM sales ORDER BY id"
        ).fetchall()

        matched = []
        for row in rows:
            rowid, status, sold_likelihood, sold_likelihood_percent, elapsed_hours, peer_count, cheaper_peer_count, repost_average_unit_price, reason, listing_json = row
            try:
                listing = json.loads(listing_json)
            except Exception:
                continue
            item_id = listing.get("itemId")
            item_name_value = listing.get("itemName")
            if item_id in item_ids or (isinstance(item_name_value, str) and item_name_value.lower() == item_name.lower()):
                matched.append((rowid, status, sold_likelihood, sold_likelihood_percent, elapsed_hours, peer_count, cheaper_peer_count, repost_average_unit_price, reason, listing))

        if not matched:
            sales_entry["matches"] = []
            set_sales_db(sales_entry)
            return

        sales_entry["matched_count"] = len(matched)
        for entry in matched:
            (rowid, status, sold_likelihood, sold_likelihood_percent, elapsed_hours, peer_count, cheaper_peer_count, repost_average_unit_price, reason, listing) = entry
            sales_entry["matches"].append(
                {
                    "id": rowid,
                    "status": status,
                    "sold_likelihood": sold_likelihood,
                    "sold_likelihood_percent": sold_likelihood_percent,
                    "elapsed_hours": elapsed_hours,
                    "peer_count": peer_count,
                    "cheaper_peer_count": cheaper_peer_count,
                    "repost_average_unit_price": repost_average_unit_price,
                    "reason": reason,
                    "listing": listing,
                }
            )
        set_sales_db(sales_entry)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Trace one item across auctioneer scan DBs and sales.db")
    parser.add_argument("--item-name", default="Northern Spices", help="Item name to trace")
    parser.add_argument("--item-ids", nargs="*", type=int, help="Additional item IDs to match")
    parser.add_argument("--scan-dir", default=".", help="Directory to search for scan DB files")
    parser.add_argument("--sales-db", default="sales.db", help="Path to sales.db")
    parser.add_argument("--item-names-json", default="infdata_item_names.json", help="Path to infdata_item_names.json")
    parser.add_argument("--scan-pattern", default="auctioneer_*.db", help="Glob pattern to find scan DB files")
    parser.add_argument("-o", "--output", default="trace_item_sales.json", help="Output JSON file")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    item_names_path = Path(args.item_names_json)
    if not item_names_path.exists():
        print(f"Item names JSON not found: {item_names_path}")
        return 1

    log_path = Path(args.output)
    if log_path.exists():
        log_path.unlink()
    log_data["item_name"] = args.item_name
    log_data["item_ids"] = []

    try:
        item_ids = load_item_ids(item_names_path, args.item_name)
    except ValueError as error:
        print(error)
        return 1

    if args.item_ids:
        item_ids.extend(args.item_ids)

    item_ids = sorted(set(item_ids))
    log_data["item_ids"] = item_ids

    scan_dir = Path(args.scan_dir)
    scan_files = sorted(scan_dir.glob(args.scan_pattern))
    if not scan_files:
        log_data["scan_dbs"] = []
    else:
        for db_path in scan_files:
            scan_db_rows(db_path, item_ids, args.item_name)

    sales_db_rows(Path(args.sales_db), item_ids, args.item_name)
    write_json_output(log_path)
    print(f"Trace written to {log_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
